### ISSUE TITLE
RuntimeError: bool value of Variable objects containing non-empty torch.cuda.FloatTensor is ambiguous

### ISSUE THREAD

**Issue by ffffuturexu** [lara-martin/ASTER#1]
Hi, I was trying to run nmt.py in Event-to-Sentence with default configs, have you got any idea why I'm getting this error?

```
Traceback (most recent call last):
File "nmt.py", line 184, in <module>
    decoder_logit = model(input_lines_src, input_lines_trg)
File "/home/wxu/anaconda2/envs/aster/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
File "/home/wxu/ASTER-master/Event-to-Sentence/model.py", line 843, in forward
    ctx_mask
File "/home/wxu/anaconda2/envs/aster/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
File "/home/wxu/ASTER-master/Event-to-Sentence/model.py", line 385, in forward
    output.append(isinstance(hidden, tuple) and hidden[0] or hidden)
File "/home/wxu/anaconda2/envs/aster/lib/python2.7/site-packages/torch/autograd/variable.py", line 123, in __bool__
    torch.typename(self.data) + " is ambiguous")
RuntimeError: bool value of Variable objects containing non-empty torch.cuda.FloatTensor is ambiguous
```

**Comment by rajammanabrolu** [comment]
The issue should be fixed with the latest commits.

**Comment by ffffuturexu** [comment]
It works, Thank you a lot.
